
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parrot.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ETIQUETAS_CERRADO = 53;
  public static final int ETIQUETA_ABIERTO = 50;
  public static final int BORRAR_PAGINA = 5;
  public static final int ALINEACION = 25;
  public static final int PAGINA = 18;
  public static final int PARAMETROS_CERRADO = 49;
  public static final int ACCIONES_ABIERTO = 43;
  public static final int ATRIBUTOS_ABIERTO = 56;
  public static final int CORCHETE_CERRADO = 40;
  public static final int NOMBRE = 45;
  public static final int ANCHO = 29;
  public static final int IZQUIERDA = 32;
  public static final int VIDEO = 22;
  public static final int ETIQUETAS = 30;
  public static final int ACCION_ABIERTO = 41;
  public static final int MENU = 23;
  public static final int IDENTIFICADOR = 60;
  public static final int SIGNO_IGUAL = 37;
  public static final int CENTRAR = 31;
  public static final int TITULO = 11;
  public static final int ETIQUETAS_ABIERTO = 52;
  public static final int PADRE = 13;
  public static final int PARAMETROS_ABIERTO = 48;
  public static final int ATRIBUTO_CERRADO = 55;
  public static final int NUEVA_PAGINA = 4;
  public static final int PARAMETRO_CERRADO = 47;
  public static final int CORCHETE_ABIERTO = 39;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 8;
  public static final int COMILLAS = 38;
  public static final int CLASE = 19;
  public static final int error = 1;
  public static final int NUMERO_HEXADECIMAL = 59;
  public static final int SIGNO_MENOR = 35;
  public static final int FECHA_MODIFICACION = 16;
  public static final int BORRAR_SITIO_WEB = 3;
  public static final int SIGNO_MAYOR = 36;
  public static final int COLOR = 26;
  public static final int ETIQUETA_CERRADO = 51;
  public static final int ACCIONES_CERRADO = 44;
  public static final int USUARIO_MODIFICACION = 17;
  public static final int FECHA_CREACION = 15;
  public static final int NUEVO_SITIO_WEB = 2;
  public static final int USUARIO_CREACION = 14;
  public static final int VALOR = 58;
  public static final int ATRIBUTOS_CERRADO = 57;
  public static final int DERECHA = 33;
  public static final int IMAGEN = 21;
  public static final int PARRAFO = 20;
  public static final int MODIFICAR_COMPONENTE = 9;
  public static final int ORIGEN = 27;
  public static final int ID_TEXTO = 10;
  public static final int AGREGAR_COMPONENTE = 7;
  public static final int ATRIBUTO_ABIERTO = 54;
  public static final int PARAMETRO_ABIERTO = 46;
  public static final int ACCION_CERRADO = 42;
  public static final int SITIO = 12;
  public static final int TEXTO = 24;
  public static final int JUSTIFICAR = 34;
  public static final int ALTURA = 28;
  public static final int MODIFICAR_PAGINA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUEVO_SITIO_WEB",
  "BORRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "BORRAR_PAGINA",
  "MODIFICAR_PAGINA",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "MODIFICAR_COMPONENTE",
  "ID_TEXTO",
  "TITULO",
  "SITIO",
  "PADRE",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "PAGINA",
  "CLASE",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TEXTO",
  "ALINEACION",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "ETIQUETAS",
  "CENTRAR",
  "IZQUIERDA",
  "DERECHA",
  "JUSTIFICAR",
  "SIGNO_MENOR",
  "SIGNO_MAYOR",
  "SIGNO_IGUAL",
  "COMILLAS",
  "CORCHETE_ABIERTO",
  "CORCHETE_CERRADO",
  "ACCION_ABIERTO",
  "ACCION_CERRADO",
  "ACCIONES_ABIERTO",
  "ACCIONES_CERRADO",
  "NOMBRE",
  "PARAMETRO_ABIERTO",
  "PARAMETRO_CERRADO",
  "PARAMETROS_ABIERTO",
  "PARAMETROS_CERRADO",
  "ETIQUETA_ABIERTO",
  "ETIQUETA_CERRADO",
  "ETIQUETAS_ABIERTO",
  "ETIQUETAS_CERRADO",
  "ATRIBUTO_ABIERTO",
  "ATRIBUTO_CERRADO",
  "ATRIBUTOS_ABIERTO",
  "ATRIBUTOS_CERRADO",
  "VALOR",
  "NUMERO_HEXADECIMAL",
  "IDENTIFICADOR"
  };
}

